// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: admin/admin_error.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace V1.Admin.Error {

  /// <summary>Holder for reflection information generated from admin/admin_error.proto</summary>
  public static partial class AdminErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for admin/admin_error.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdminErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdhZG1pbi9hZG1pbl9lcnJvci5wcm90bxIOdjEuYWRtaW4uZXJyb3IqYwoL",
            "RXJyb3JSZWFzb24SCwoHU1VDQ0VTUxAAEgoKBkZBSUxFRBABEg8KC0lOVkFM",
            "SURfVVJMEGUSFgoSSU5WQUxJRF9GRUFUVVJFX0lEEGYSEgoNU1RPUkFHRV9F",
            "UlJPUhDJAUIUWhJhcGkvdjEvYWRtaW47YWRtaW5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::V1.Admin.Error.ErrorReason), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorReason {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("SUCCESS")] Success = 0,
    /// <summary>
    /// 错误
    /// </summary>
    [pbr::OriginalName("FAILED")] Failed = 1,
    /// <summary>
    /// 客户端错误
    /// </summary>
    [pbr::OriginalName("INVALID_URL")] InvalidUrl = 101,
    /// <summary>
    /// featureId无效：排行榜没有此配置
    /// </summary>
    [pbr::OriginalName("INVALID_FEATURE_ID")] InvalidFeatureId = 102,
    /// <summary>
    /// 服务器错误
    /// </summary>
    [pbr::OriginalName("STORAGE_ERROR")] StorageError = 201,
  }

  #endregion

}

#endregion Designer generated code
