using System.Collections.Generic;
namespace AppBase.Config
{
    public static class ConfigNames
    {
        public static List<string> keyNames = new List<string>()
        {
            "ActivityConfig",
            "ActivityDataConfig",
            "AnalyticsEventConfig",
            "AnalyticsEventPropertiesConfig",
            "AnalyticsThirdPartyConfig",
            "AnalyticsUserAssetConfig",
            "AnalyticsUserPropertiesConfig",
            "AnalyticsUserStepConfig",
            "BackgroundConfig",
            "BlossomDealConfig",
            "CensorshipConfig",
            "Chinese_Simplified",
            "Chinese_Traditional",
            "CloverTreasureRewardConfig",
            "CloverTreasureSeasonConfig",
            "DailyBonusConfig",
            "English",
            "FestiveAirConfig",
            "GlobalConfig",
            "IAPConfig",
            "IslandExpeditionConfig",
            "ItemConfig",
            "LeaderboardConfig",
            "LevelChestConfig",
            "LevelFeatureConfig",
            "LevelKeepScoreConfig",
            "LobbyModelConfig",
            "LocalNotificationChannelConfig",
            "LocalNotificationConfig",
            "MatchConfig",
            "MatchLevelConfig",
            "ModelConfig",
            "OneByOneConditionConfig",
            "OneByOneEventConfig",
            "OneByOneFilterConfig",
            "OneByOnePoolConfig",
            "OneByOneTriggerConfig",
            "PartConfig",
            "RandomListConfig",
            "RocketRaceRobotConfig",
            "RocketRaceRobotNameConfig",
            "RocketTreasureConfig",
            "ShopConfig",
            "StarChestConfig",
            "SupportConfig",
            "TeamBadgeConfig",
            "TeamConfig",
            "WeeklyContestConfig"
        };
    }
}
